fix Class.get(): it was relying on self._marker, and that value was different for FileClass instances. the _marker is moved to module globals.
fixes error in test testImportExport:
 TypeError: new property "comment" not a string: []


git-svn-id: https://svn.roundup-tracker.org/svnroot/roundup/trunk@2763 57a73879-2fb5-44c3-a270-3262357dd7e2